// LOGIN:
export const LOGIN_ADMIN = "LOGIN_ADMIN";
export const LOGIN_ADMIN_SUCCESS = "LOGIN_ADMIN_SUCESS";
export const LOGIN_ADMIN_FAILED = "LOGIN_ADMIN_FAILED";

// USERS:
export const USERS = "USERS";
export const USERS_SUCCESS = "USERS_SUCESS";
export const USERS_FAILED = "USERS_FAILED";
// DELETE USER:

export const USERS_DELETE_SUCCESS = "USERS_DELETE_SUCESS";
export const USERS_DELETE_FAILED = "USERS_DELETE_FAILED";

// ORDERS:
export const ORDERS = "ORDERS";
export const ORDERS_SUCCESS = "ORDERS_SUCESS";
export const ORDERS_FAILED = "ORDERS_FAILED";
// Approved ORDER:
export const ORDERS_APPROVED_SUCCESS = "ORDERS_APPROVED_SUCESS";
export const ORDERS_APPROVED_FAILED = "ORDERS_APPROVED_FAILED";
/* // REJECTED ORDER:
export const ORDERS_REJECTED_SUCCESS = "ORDERS_REJECTED_SUCESS";
export const ORDERS_REJECTED_FAILED = "ORDERS_REJECTED_FAILED"; */

// DELETE ORDER:

export const ORDERS_DELETE_SUCCESS = "ORDERS_DELETE_SUCESS";
export const ORDERS_DELETE_FAILED = "ORDERS_DELETE_FAILED";

// INCOME:
export const INCOME = "INCOME";
export const INCOME_SUCCESS = "INCOME_SUCCESS";
export const INCOME_FAILED = "INCOME_FAILED";

// PRODUCTS:

export const PRODUCTS = "PRODUCTS";
export const PRODUCTS_SUCCESS = "PRODUCTS_SUCESS";
export const PRODUCTS_FAILED = "PRODUCTS_FAILED";
// PRDUCT DELETE
export const PRODUCTS_DELETE = "PRODUCTS_DELETE";
export const PRODUCTS_DELETE_SUCCESS = "PRODUCTS_DELETE_SUCESS";
export const PRODUCTS_DELETE_FAILED = "PRODUCTS_DELETE_FAILED";
// PRDUCT UPDATE
export const PRODUCTS_UPDATE = "PRODUCTS_UPDATE";
export const PRODUCTS_UPDATE_SUCCESS = "PRODUCTS_UPDATE_SUCESS";
export const PRODUCTS_UPDATE_FAILED = "PRODUCTS_UPDATE_FAILED";
// PRDUCT ADD
export const PRODUCTS_ADD = "PRODUCTS_ADD";
export const PRODUCTS_ADD_SUCCESS = "PRODUCTS_ADD_SUCESS";
export const PRODUCTS_ADD_FAILED = "PRODUCTS_ADD_FAILED";
