// PRODUCTS ACTIONS

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";

// PRODUCT ACTIONS
export const GET_ONE_PRODUCT = "GET_ONE_PRODUCT";
export const GET_ONE_PRODUCT_SUCCESS = "GET_ONE_PRODUCT_SUCCESS";
export const GET_ONE_PRODUCT_FAILED = "GET_ONE_PRODUCT_FAILED";

// CART ACTIONS
export const ADD_PRODUCT_CART = "ADD_PRODUCT_CART";
export const DELETE_PRODUCT_CART = "DELETE_PRODUCT_CART";
export const UPDATE_PRODUCT_CART = "UPDATE_PRODUCT_CART";

// USER ACTIONS:
// REGISTER:
export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

// LOGIN:
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

// CART ACTIONS

export const TOGGLE_PRODUCT_SAVED = "TOGGLE_PRODUCT_SAVED";
export const DELETE_PRODUCT_SAVED = "DELETE_PRODUCT_SAVED";
